# Lab 2 in Rmarkdown

## Please submit this assignment as a well formatted, easy to read printed, hard-copy R Markdown file.

1. Choose some real data.  Explain the data, why it's interesting and use some summary statistics (in line code) to describe this data.

2. Use a code chunk to explore it further -- missing data by variable? Interesting stuff? 

3. Explore your data further  making sure you do use each of these:

- headers
- ordered lists
- links
- an image
- a table

4.  Make multiple, correctly-sized  plots on a single row (for example):

```{r, echo = FALSE, figures-side, fig.show="hold", out.width="50%"}
par(mar = c(4, 4, .1, .1))
plot(cars)
plot(mpg ~ hp, data = mtcars, pch = 19)
```


5. Using a well-formatted code chunk answer this question:  Which homeworlds have the greatest percentage of individuals with BMI’s greater than the average for each homework?  Make sure you are clear about what you do with missing data.     

6. Something else neat with your data that shows your Rmarkdown skills and why your dataset is of interest.    
    
